package com.ama.jobmate.common.config;

import com.ama.jobmate.entity.Category;
import com.ama.jobmate.repository.CategoryRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class CategoryDataInitializer implements CommandLineRunner {

    private final CategoryRepository categoryRepository;

    @Override
    @Transactional
    public void run(String... args) {
        if (categoryRepository.count() > 0) {
            return;
        }

        // =========================
        // JOB
        // =========================
        Category itRoot = save("JOB", "IT개발·데이터", 1, null);

        Category jobRole = save("JOB", "직무·직업", 2, itRoot);
        Category specialty = save("JOB", "전문분야", 2, itRoot);
        Category jobTech = save("JOB", "기술스택", 2, itRoot);

        saveChildren("JOB", jobRole,
                "개발PM",
                "게임개발",
                "기술지원",
                "데이터 사이언티스트",
                "데이터분석가",
                "데이터엔지니어",
                "백엔드/서버개발",
                "보안관제",
                "보안컨설팅",
                "앱개발",
                "웹개발",
                "웹마스터",
                "유지보수",
                "정보보안",
                "퍼블리셔",
                "프론트엔드",
                "BI 엔지니어",
                "CISO",
                "CPO",
                "DBA",
                "FAE",
                "GM(게임운영)",
                "ICT컨설팅",
                "IT컨설팅",
                "QA/테스터",
                "SE(시스템엔지니어)",
                "SI개발",
                "SQA"
        );

        saveChildren("JOB", specialty,
                "검색엔진",
                "네트워크",
                "데이터라벨링",
                "데이터마이닝",
                "데이터시각화",
                "딥러닝",
                "머신러닝",
                "메타버스",
                "모델링",
                "모의해킹",
                "미들웨어",
                "반응형웹",
                "방화벽",
                "블록체인",
                "빅데이터",
                "빌링",
                "솔루션",
                "스크립트",
                "신경망",
                "아키텍처",
                "악성코드",
                "알고리즘",
                "암호화폐",
                "영상처리",
                "웹표준·웹접근성",
                "음성인식",
                "이미지프로세싱",
                "인터페이스",
                "인프라",
                "임베디드",
                "자율주행",
                "정보통신",
                "챗봇",
                "취약점진단",
                "컴퓨터비전",
                "크로스브라우징",
                "크로스플랫폼",
                "크롤링",
                "클라우드",
                "클라이언트",
                "텍스트마이닝",
                "트러블슈팅",
                "펌웨어",
                "플러그인",
                "핀테크",
                "헬스케어",
                "AI(인공지능)",
                "API",
                "APM",
                "AR(증강현실)",
                "Dapp",
                "DBMS",
                "DevOps",
                "DID",
                "DLP",
                "DW",
                "ERP",
                "ETL",
                "FPGA",
                "GIS",
                "H/W",
                "HTTP",
                "IDC",
                "IS",
                "IoT",
                "ISMS",
                "MCU",
                "MMORPG",
                "Nginx",
                "NLP(자연어처리)",
                "NLU(자연어이해)",
                "OCR",
                "OLAP",
                "RDBMS",
                "RPA",
                "RTOS",
                "S/W",
                "SAP",
                "SDK",
                "SOA",
                "STT",
                "TTS",
                "UTM",
                "VDI",
                "VMware",
                "VoIP",
                "VPN",
                "VR(가상현실)",
                "WCF",
                "Windows"
        );

        saveChildren("JOB", jobTech,
                "그누보드",
                "라즈베리파이",
                "쉘스크립트",
                "스마트컨트랙트",
                "아두이노",
                "액션스크립트",
                "어셈블리",
                "와이어샤크",
                "임베디드리눅스",
                "파워빌더",
                "풀스택",
                ".NET",
                "ABAP",
                "AIX",
                "Ajax",
                "Android",
                "Angular",
                "Apache",
                "ArcGIS",
                "ASP",
                "ASP.NET",
                "AWS",
                "Azure",
                "Bootstrap",
                "C#",
                "C++",
                "CentOS",
                "COBOL",
                "CSS",
                "CSS3",
                "C언어",
                "Delphi",
                "Directx",
                "Django",
                "Docker",
                "Eclipse",
                "ECMAScript",
                "ElasticStack",
                "Flask",
                "FLEX",
                "Flutter",
                "GCP",
                "Git",
                "GoLang",
                "GraphQL",
                "Groovy",
                "Gulp",
                "Hadoop",
                "HTML",
                "HTML5",
                "IaaS",
                "iBATIS",
                "iOS",
                "Java",
                "Javascript",
                "Jenkins",
                "JPA",
                "jQuery",
                "JSP",
                "Kafka",
                "Keras",
                "Kotlin",
                "Kubernetes",
                "LabVIEW",
                "Linux",
                "Logstash",
                "Lucene",
                "MacOS",
                "MariaDB",
                "Matlab",
                "Maven",
                "MFC",
                "MongoDB",
                "MSSQL",
                "MyBatis",
                "MySQL",
                "Node.js",
                "NoSQL",
                "Objective-C",
                "OpenCV",
                "OpenGL",
                "OracleDB",
                "OSS",
                "PaaS",
                "Pandas",
                "Perl",
                "PHP",
                "PL/SQL",
                "PostgreSQL",
                "Pro-C",
                "Python",
                "Pytorch",
                "QGIS",
                "Qt",
                "R",
                "React",
                "React-Native",
                "ReactJS",
                "Redis",
                "Redux",
                "RestAPI",
                "Ruby",
                "SaaS",
                "SAS",
                "Scala",
                "Servlet",
                "Solaris",
                "Solidity",
                "Spark",
                "Splunk",
                "Spring",
                "SpringBoot",
                "SQL",
                "SQLite",
                "SVN",
                "Swift",
                "Sybase",
                "Tensorflow",
                "Tomcat",
                "TypeScript",
                "Ubuntu",
                "Unity",
                "Unix",
                "Unreal",
                "VB.NET",
                "Verilog",
                "Vert.x",
                "VisualBasic",
                "VisualC++",
                "Vue.js",
                "WAS",
                "WebGL",
                "Webpack",
                "WebRTC",
                "WPF",
                "XML"
        );

        // =========================
        // STACK
        // =========================
        Category lang = save("STACK", "언어", 1, null);
        Category frontend = save("STACK", "프론트엔드", 1, null);
        Category backend = save("STACK", "백엔드", 1, null);
        Category mobile = save("STACK", "모바일", 1, null);
        Category db = save("STACK", "DB", 1, null);
        Category infra = save("STACK", "인프라/클라우드", 1, null);
        Category devops = save("STACK", "DevOps", 1, null);
        Category dataAi = save("STACK", "데이터/AI", 1, null);
        Category etc = save("STACK", "기타", 1, null);

        saveChildren("STACK", lang,
                "Java",
                "Javascript",
                "TypeScript",
                "Python",
                "Kotlin",
                "C언어",
                "C#",
                "C++",
                "GoLang",
                "PHP",
                "Swift",
                "R",
                "Scala",
                "Ruby",
                "Perl",
                "COBOL",
                "ABAP",
                "Delphi",
                "Groovy",
                "VisualBasic",
                "VisualC++",
                "Objective-C",
                "Pro-C",
                "Solidity",
                "VB.NET",
                "Verilog",
                "XML"
        );

        saveChildren("STACK", frontend,
                "HTML",
                "HTML5",
                "CSS",
                "CSS3",
                "Ajax",
                "jQuery",
                "React",
                "ReactJS",
                "Vue.js",
                "Angular",
                "Bootstrap",
                "Webpack",
                "WebGL",
                "WebRTC",
                "ECMAScript",
                "Gulp",
                "Redux",
                "Servlet",
                "JSP",
                "ASP",
                "ASP.NET",
                "WPF",
                "FLEX"
        );

        saveChildren("STACK", backend,
                "Spring",
                "SpringBoot",
                "JPA",
                "MyBatis",
                "iBATIS",
                "Node.js",
                "Django",
                "Flask",
                "Tomcat",
                "RestAPI",
                "GraphQL",
                "Nginx",
                "WAS",
                "Apache",
                "Lucene",
                "Vert.x",
                "OSS"
        );

        saveChildren("STACK", mobile,
                "Android",
                "iOS",
                "Flutter",
                "React-Native",
                "Unity",
                "Unreal",
                "Directx"
        );

        saveChildren("STACK", db,
                "MySQL",
                "MariaDB",
                "MSSQL",
                "MongoDB",
                "OracleDB",
                "PostgreSQL",
                "SQLite",
                "Redis",
                "NoSQL",
                "PL/SQL",
                "SQL",
                "DBMS",
                "RDBMS",
                "Sybase"
        );

        saveChildren("STACK", infra,
                "AWS",
                "Azure",
                "GCP",
                "Linux",
                "Ubuntu",
                "Unix",
                "CentOS",
                "Windows",
                "MacOS",
                "Docker",
                "Kubernetes",
                "Terraform",
                "IaaS",
                "PaaS",
                "SaaS",
                "AIX",
                "Solaris",
                "VMware",
                "IDC",
                "VPN",
                "VDI"
        );

        saveChildren("STACK", devops,
                "Git",
                "Jenkins",
                "SVN",
                "Splunk",
                "Logstash",
                "ElasticStack",
                "Kafka",
                "Docker",
                "Kubernetes",
                "Maven"
        );

        saveChildren("STACK", dataAi,
                "Pandas",
                "Hadoop",
                "Spark",
                "Tensorflow",
                "Pytorch",
                "Keras",
                "OpenCV",
                "Matlab",
                "QGIS",
                "ArcGIS",
                "LabVIEW"
        );

        saveChildren("STACK", etc,
                "그누보드",
                "라즈베리파이",
                "쉘스크립트",
                "스마트컨트랙트",
                "아두이노",
                "액션스크립트",
                "어셈블리",
                "와이어샤크",
                "임베디드리눅스",
                "파워빌더",
                "풀스택",
                ".NET",
                "Eclipse",
                "Git",
                "Qt",
                "MFC",
                "SDK",
                "FPGA",
                "MCU",
                "RTOS"
        );
    }

    private Category save(String type, String name, Integer level, Category parent) {
        Category category = Category.builder()
                .type(type)
                .name(name)
                .level(level)
                .parent(parent)
                .build();
        return categoryRepository.save(category);
    }

    private void saveChildren(String type, Category parent, String... names) {
        for (String name : names) {
            save(type, name, parent.getLevel() + 1, parent);
        }
    }
}